kind: Service
apiVersion: v1
metadata:
  name: nilai-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: siswa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nilai-deploy
  namespace: production
spec:
  selector:
    matchLabels:
      app: siswa
  replicas: 2
  template:
    metadata:
      labels:
        app: siswa
    spec:
      containers:
      - name: php-nilai
        image: farman17/aplikasi-nilaisiswa
        ports:
          - containerPort: 80
       

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nilai-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: siswa.dailybugis.my.id
    http:
      paths:
      #- path: /
      - backend:
          serviceName: nilai-service
          servicePort: 80

